# Generated by Django 3.2.5 on 2021-12-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pollmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_question', models.CharField(max_length=200)),
                ('poll_option_one', models.CharField(max_length=100)),
                ('poll_option_two', models.CharField(max_length=100)),
                ('poll_option_three', models.CharField(max_length=100)),
                ('poll_option_one_count', models.IntegerField()),
                ('poll_option_two_count', models.IntegerField()),
                ('poll_option_three_count', models.IntegerField()),
            ],
        ),
    ]
