# Generated by Django 3.2.5 on 2021-12-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollmodel',
            name='poll_question',
            field=models.TextField(max_length=200),
        ),
    ]
